### ISSUE TITLE
Error WoocommerceProductsService -> HttpClient

### ISSUE THREAD

**Issue by salvadorcoronel** [angular-studio/wooApi#4] opened 2019-09-27 18:59 UTC
Current Workspace

Angular CLI: 8.3.2
Node: 10.15.3
OS: darwin x64
Angular: 8.2.4
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

In Package.json I have...
"ngx-wooapi": "^7.0.0-beta.1",

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.803.2
@angular-devkit/build-angular     0.803.2
@angular-devkit/build-optimizer   0.803.2
@angular-devkit/build-webpack     0.803.2
@angular-devkit/core              8.3.2
@angular-devkit/schematics        8.3.2
@angular/cli                      8.3.2
@angular/http                     7.2.15
@ngtools/webpack                  8.3.2
@schematics/angular               8.3.2
@schematics/update                0.803.2
rxjs                              6.4.0
typescript                        3.5.3
webpack                           4.39.2

I have done the step by step of the following tutorial https://angular-studio.github.io/wooApi/v5/, but I get this error

`core.js:6014 ERROR Error: Uncaught (in promise): NullInjectorError: StaticInjectorError(AppModule)[WoocommerceProductsService -> HttpClient]: 
  StaticInjectorError(Platform: core)[WoocommerceProductsService -> HttpClient]: 
    NullInjectorError: No provider for HttpClient!
NullInjectorError: StaticInjectorError(AppModule)[WoocommerceProductsService -> HttpClient]: 
  StaticInjectorError(Platform: core)[WoocommerceProductsService -> HttpClient]: 
    NullInjectorError: No provider for HttpClient!`

**Comment by prosenjit-manna** [comment] 2019-09-28 08:10
Please add dependency HttpClientModule in your module.

import { HttpClientModule } from '@angular/common/http';

https://angular.io/guide/http

**Comment by salvadorcoronel** [comment] 2019-09-28 14:38
Hi @prosenjit-manna 
I have added the HttpClientModule on my app.module.ts, check this...

`import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';

import { HttpClientModule, HTTP_INTERCEPTORS } from '@angular/common/http';
import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { HomeComponent } from './ui/home/home.component';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { WoocommerceProductsService, WoocommerceHelperService } from 'ngx-wooapi';
import { AppInterceptor } from './app.interceptor';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
  ],
  imports: [
    BrowserModule,
    HttpClientModule,
    AppRoutingModule,
    BrowserAnimationsModule,
    CommonModule
  ],
  providers: [
    WoocommerceProductsService,
    WoocommerceHelperService,
    { provide: HTTP_INTERCEPTORS, useClass: AppInterceptor, multi: true },
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }
`

**Comment by prosenjit-manna** [comment] 2019-11-14 14:30
Closing this for now. I think the issue is solved.

**Closed as completed by prosenjit-manna** 2019-11-14 14:30 UTC
